# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 20170816_FinalizeSectionLines.py
# Created on: 2017-08-16 07:44:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 20170816_FinalizeSectionLines <Section_Lines__VERY_IMPORTANT__Definition_Query_out_your_section_before_running_tool_> <Trim_Tolerance> <Extend_Length_Tolerance> <Generalize_Tolerance> 
# Description: Trim, Extend, and Generalize lines
# Intended for streamlined editing of PLSS quarter/section lines
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
Section_Lines__VERY_IMPORTANT__Definition_Query_out_your_section_before_running_tool_ = arcpy.GetParameterAsText(0)

Trim_Tolerance = arcpy.GetParameterAsText(1)
if Trim_Tolerance == '#' or not Trim_Tolerance:
    Trim_Tolerance = "500 Feet" # provide a default value if unspecified

Extend_Length_Tolerance = arcpy.GetParameterAsText(2)
if Extend_Length_Tolerance == '#' or not Extend_Length_Tolerance:
    Extend_Length_Tolerance = "500 Feet" # provide a default value if unspecified

Generalize_Tolerance = arcpy.GetParameterAsText(3)
if Generalize_Tolerance == '#' or not Generalize_Tolerance:
    Generalize_Tolerance = "3500 Feet" # provide a default value if unspecified

# Local variables:
Remove_Vertices_Test__3_ = Section_Lines__VERY_IMPORTANT__Definition_Query_out_your_section_before_running_tool_
Output_Feature_Class__2_ = Remove_Vertices_Test__3_
Output_Feature_Class__3_ = Output_Feature_Class__2_

# Process: Trim Line
arcpy.TrimLine_edit(Section_Lines__VERY_IMPORTANT__Definition_Query_out_your_section_before_running_tool_, Trim_Tolerance, "DELETE_SHORT")

# Process: Extend Line
arcpy.ExtendLine_edit(Remove_Vertices_Test__3_, Extend_Length_Tolerance, "EXTENSION")

# Process: Generalize
arcpy.Generalize_edit(Output_Feature_Class__2_, Generalize_Tolerance)

